import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import type { CleanupCandidate, CleanupRecord, DockerResult, DuplicateResult, ScanProgress, ScanSummary } from "./types";

const nav = ["Overview", "Storage", "Large Files", "Duplicates", "Development", "Docker", "Cleanup", "History", "Settings"];
const bytes = (n = 0) => n < 1024 ** 2 ? `${Math.round(n / 1024)} KB` : n < 1024 ** 3 ? `${(n / 1024 ** 2).toFixed(1)} MB` : `${(n / 1024 ** 3).toFixed(1)} GB`;
const shortPath = (value: string) => value.length > 86 ? `…${value.slice(-85)}` : value;

export function App() {
  const [root, setRoot] = useState<string>(); const [progress, setProgress] = useState<ScanProgress>(); const [summary, setSummary] = useState<ScanSummary>(); const [scanning, setScanning] = useState(false); const [page, setPage] = useState("Overview"); const [error, setError] = useState<string>();
  const [duplicates, setDuplicates] = useState<DuplicateResult>(); const [duplicateLoading, setDuplicateLoading] = useState(false); const [docker, setDocker] = useState<DockerResult>(); const [history, setHistory] = useState<CleanupRecord[]>([]); const [notice, setNotice] = useState<string>();
  useEffect(() => { let disposed = false; const promise = listen<ScanProgress>("scan-progress", event => { if (!disposed) setProgress(event.payload); }); return () => { disposed = true; void promise.then(unlisten => unlisten()); }; }, []);
  useEffect(() => { if (page === "Docker" && !docker) void invoke<DockerResult>("docker_status").then(setDocker).catch(value => setError(String(value))); if (page === "History") void invoke<CleanupRecord[]>("cleanup_history").then(setHistory).catch(value => setError(String(value))); }, [page, docker]);
  const categories = useMemo(() => Object.entries(summary?.categories ?? {}).sort((a,b) => b[1] - a[1]), [summary]);
  async function chooseAndScan() { const folder = await open({ directory: true, multiple: false, title: "Choose a disk or folder to inspect" }); if (typeof folder !== "string") return; setRoot(folder); setError(undefined); setNotice(undefined); setSummary(undefined); setDuplicates(undefined); setDocker(undefined); setProgress(undefined); setScanning(true); try { setSummary(await invoke<ScanSummary>("scan_folder", { root: folder, mode: "full" })); } catch (value) { setError(String(value)); } finally { setScanning(false); } }
  async function cancel() { await invoke("cancel_scan"); }
  async function loadDuplicates() { setDuplicateLoading(true); setError(undefined); try { setDuplicates(await invoke<DuplicateResult>("find_duplicates")); } catch (value) { setError(String(value)); } finally { setDuplicateLoading(false); } }
  async function clean(candidate: CleanupCandidate) { if (!confirm(`${candidate.title}\n\n${candidate.path}\n\n${bytes(candidate.estimated_bytes)} will be moved to your system Trash/Recycle Bin. Continue?`)) return; try { await invoke("cleanup_candidate", { id: candidate.id }); setSummary(current => current ? { ...current, development: current.development.filter(item => item.id !== candidate.id) } : current); setNotice("The selected target was moved to the system Trash/Recycle Bin. Check History for the cleanup record."); } catch (value) { setError(String(value)); } }
  async function snapshot() { if (!summary || !root) return; try { await invoke("save_snapshot", { summary, root }); setNotice("Snapshot saved locally. It contains metadata only, never file contents."); } catch (value) { setError(String(value)); } }
  const content = !summary ? <section className="empty"><h2>Start with a folder or disk</h2><p>DiskScope reads metadata locally and reports permission issues instead of hiding them.</p><button onClick={chooseAndScan}>Start a scan</button></section> : page === "Storage" ? <Storage categories={categories} /> : page === "Large Files" ? <LargeFiles summary={summary} /> : page === "Development" ? <Development items={summary.development} onClean={clean} /> : page === "Cleanup" ? <Cleanup items={summary.development} onClean={clean} /> : page === "Duplicates" ? <Duplicates data={duplicates} loading={duplicateLoading} onLoad={loadDuplicates} /> : page === "Docker" ? <Docker data={docker} /> : page === "History" ? <History records={history} /> : page === "Settings" ? <Settings /> : <Overview summary={summary} categories={categories} onSnapshot={snapshot} />;
  return <div className="app"><a className="skip" href="#content">Skip navigation</a><aside><div className="brand"><span>◒</span> DiskScope</div><nav aria-label="Primary navigation">{nav.map(item => <button className={page === item ? "active" : ""} onClick={() => setPage(item)} key={item}>{item}</button>)}</nav><div className="privacy">Local-first<br/>No files leave this device.</div></aside><main id="content"><header><div><p className="eyebrow">{page}</p><h1>{root ? shortPath(root) : "Understand your storage"}</h1><p className="muted">Inspect first. Explain second. Delete only after explicit confirmation.</p></div><div className="actions"><button className="secondary" disabled={scanning} onClick={chooseAndScan}>{root ? "Choose another folder" : "Select a folder"}</button>{scanning && <button className="danger" onClick={cancel}>Cancel scan</button>}</div></header>{error && <section className="notice error" role="alert">{error}</section>}{notice && <section className="notice" role="status">{notice}</section>}{scanning && <section className="scan" aria-live="polite"><div className="spinner"/><div><strong>Scanning safely…</strong><p>{progress?.current_path ?? "Preparing traversal"}</p><small>{progress?.entries_seen.toLocaleString() ?? 0} entries · {bytes(progress?.bytes_seen)} · {progress?.inaccessible_paths ?? 0} inaccessible paths</small></div></section>}{content}</main></div>;
}
function Overview({ summary, categories, onSnapshot }: { summary: ScanSummary; categories: [string, number][]; onSnapshot: () => void }) { return <><section className="stats"><article><span>Scanned</span><strong>{bytes(summary.bytes)}</strong><small>{summary.entries.toLocaleString()} filesystem entries</small></article><article><span>Permission issues</span><strong>{summary.errors}</strong><small>Reported for review</small></article><article><span>Review candidates</span><strong>{summary.development.length}</strong><small>No automatic cleanup</small></article></section><Storage categories={categories.slice(0, 7)} /><section className="safety"><div><h2>Snapshot comparison</h2><p>Save this scan’s metadata locally to compare storage growth later.</p></div><button className="secondary" onClick={onSnapshot}>Save snapshot</button></section></> }
function Storage({ categories }: { categories: [string, number][] }) { const largest = categories[0]?.[1] ?? 1; return <section className="panel"><div className="panelTitle"><h2>Storage breakdown</h2><span>Explainable rules</span></div>{categories.length ? <ul className="categoryList">{categories.map(([name, total]) => <li key={name}><span>{name}</span><div><i style={{ width: `${Math.max(4, total / largest * 100)}%` }}/><b>{bytes(total)}</b></div></li>)}</ul> : <p className="muted">No files were found under this root.</p>}</section> }
function LargeFiles({ summary }: { summary: ScanSummary }) { return <section className="panel"><div className="panelTitle"><h2>Largest files</h2><span>Top 200 retained during scan</span></div><div className="fileList">{summary.large_files.map(file => <div key={file.path}><span title={file.path}>{shortPath(file.path)}</span><em>{file.category}</em><b>{bytes(file.size)}</b></div>)}</div></section> }
function Development({ items, onClean }: { items: CleanupCandidate[]; onClean: (item: CleanupCandidate) => void }) { return <section className="panel"><div className="panelTitle"><h2>Development & build caches</h2><span>Every recommendation is explained</span></div><Candidates items={items} onClean={onClean} /></section> }
function Cleanup({ items, onClean }: { items: CleanupCandidate[]; onClean: (item: CleanupCandidate) => void }) { const reclaimable = items.reduce((sum, item) => sum + item.estimated_bytes, 0); return <section className="panel"><div className="panelTitle"><div><h2>Cleanup review</h2><p className="muted">{bytes(reclaimable)} selected only after confirmation</p></div><span>System Trash / Recycle Bin</span></div><Candidates items={items} onClean={onClean} /></section> }
function Candidates({ items, onClean }: { items: CleanupCandidate[]; onClean: (item: CleanupCandidate) => void }) { return items.length ? <div className="candidates">{items.map(item => <article key={item.id}><div><span className={`risk ${item.risk.replaceAll(" ", "-")}`}>{item.risk}</span><h3>{item.title}</h3><p title={item.path}>{shortPath(item.path)}</p><small>{item.reason}</small></div><div className="candidateAction"><b>{bytes(item.estimated_bytes)}</b><button onClick={() => onClean(item)}>Review & clean</button></div></article>)}</div> : <p className="muted">No recognized developer caches were found in the selected root.</p> }
function Duplicates({ data, loading, onLoad }: { data?: DuplicateResult; loading: boolean; onLoad: () => void }) { return <section className="panel"><div className="panelTitle"><div><h2>Exact duplicates</h2><p className="muted">Size → partial hash → full SHA-256 confirmation</p></div><button disabled={loading} onClick={onLoad}>{loading ? "Checking…" : "Find duplicates"}</button></div>{data?.limited && <p className="notice">Scan result hit the safety memory limit; run a narrower folder scan for exhaustive duplicate results.</p>}{data && (data.groups.length ? <div className="candidates">{data.groups.map(group => <article key={group.hash}><div><span className="risk REVIEW">EXACT MATCH</span><h3>{group.files.length} identical files</h3><p>{group.files.map(shortPath).join(" · ")}</p><small>SHA-256 {group.hash.slice(0, 18)}…</small></div><div className="candidateAction"><b>{bytes(group.bytes_per_file * (group.files.length - 1))}</b><small>potential reclaim</small></div></article>)}</div> : <p className="muted">No exact duplicate groups found.</p>)}</section> }
function Docker({ data }: { data?: DockerResult }) { return <section className="panel"><div className="panelTitle"><h2>Docker inspection</h2><span>Read-only `docker system df -v`</span></div>{!data ? <p className="muted">Checking local Docker CLI…</p> : data.available ? <pre>{data.detail}</pre> : <p className="muted">{data.detail}</p>}<section className="safety"><h2>Volume safety</h2><p>DiskScope does not delete Docker volumes through this view. Volumes require a separate HIGH RISK review.</p></section></section> }
function History({ records }: { records: CleanupRecord[] }) { return <section className="panel"><div className="panelTitle"><h2>Cleanup history</h2><span>Local records only</span></div>{records.length ? <div className="fileList">{records.map(record => <div key={`${record.timestamp}-${record.paths[0]}`}><span>{record.paths.map(shortPath).join(", ")}</span><em>{record.method}</em><b>{bytes(record.bytes)}</b></div>)}</div> : <p className="muted">No cleanup actions recorded on this device.</p>}</section> }
function Settings() { return <section className="panel"><h2>Safety defaults</h2><ul className="settings"><li><b>Local-first</b><span>No account, file upload, or telemetry.</span></li><li><b>Symlink policy</b><span>Links are reported but never traversed or cleaned.</span></li><li><b>Cleanup policy</b><span>Explicit confirmation, selected-root validation, then system Trash / Recycle Bin.</span></li><li><b>Docker volumes</b><span>HIGH RISK; not available in generic cleanup.</span></li></ul></section> }
