import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import type { ScanProgress, ScanSummary } from "./types";

const nav = ["Overview", "Storage", "Large Files", "Duplicates", "Development", "Docker", "Cleanup", "History", "Settings"];
const bytes = (n = 0) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 1, style: "unit", unit: "gigabyte", unitDisplay: "narrow" }).format(n / 1024 ** 3);
export function App() {
  const [root, setRoot] = useState<string>(); const [progress, setProgress] = useState<ScanProgress>(); const [summary, setSummary] = useState<ScanSummary>(); const [scanning, setScanning] = useState(false); const [page, setPage] = useState("Overview"); const [error, setError] = useState<string>();
  useEffect(() => { let cancel = false; void listen<ScanProgress>("scan-progress", e => { if (!cancel) setProgress(e.payload); }).then(unlisten => { if (cancel) unlisten(); else return () => unlisten(); }); return () => { cancel = true; }; }, []);
  const categories = useMemo(() => Object.entries(summary?.categories ?? {}).sort((a,b) => b[1] - a[1]), [summary]);
  async function chooseAndScan() { const folder = await open({ directory: true, multiple: false, title: "Choose a disk or folder to inspect" }); if (typeof folder !== "string") return; setRoot(folder); setError(undefined); setSummary(undefined); setProgress(undefined); setScanning(true); try { setSummary(await invoke<ScanSummary>("scan_folder", { root: folder, mode: "full" })); } catch (e) { setError(String(e)); } finally { setScanning(false); } }
  async function cancel() { await invoke("cancel_scan"); }
  return <div className="app"><a className="skip" href="#content">Skip navigation</a><aside><div className="brand"><span>◒</span> DiskScope</div><nav aria-label="Primary navigation">{nav.map(item => <button className={page === item ? "active" : ""} onClick={() => setPage(item)} key={item}>{item}</button>)}</nav><div className="privacy">Local-first<br/>No files leave this device.</div></aside><main id="content"><header><div><p className="eyebrow">{page}</p><h1>{root ? root : "Understand your storage"}</h1><p className="muted">Inspect first. Explain second. Delete only after explicit confirmation.</p></div><div className="actions"><button className="secondary" disabled={scanning} onClick={chooseAndScan}>{root ? "Choose another folder" : "Select a folder"}</button>{scanning && <button className="danger" onClick={cancel}>Cancel scan</button>}</div></header>{error && <section className="notice" role="alert">Scan failed: {error}</section>}{!root && <section className="empty"><h2>Start with a folder or disk</h2><p>DiskScope reads metadata locally and reports permission issues instead of hiding them.</p><button onClick={chooseAndScan}>Start a scan</button></section>}{scanning && <section className="scan" aria-live="polite"><div className="spinner"/><div><strong>Scanning safely…</strong><p>{progress?.current_path ?? "Preparing traversal"}</p><small>{progress?.entries_seen.toLocaleString() ?? 0} entries · {bytes(progress?.bytes_seen)} · {progress?.inaccessible_paths ?? 0} inaccessible paths</small></div></section>}{summary && <><section className="stats"><article><span>Scanned</span><strong>{bytes(summary.bytes)}</strong><small>{summary.entries.toLocaleString()} filesystem entries</small></article><article><span>Permission issues</span><strong>{summary.errors}</strong><small>Reviewable, never silently ignored</small></article><article><span>Potentially reclaimable</span><strong>—</strong><small>Requires a dedicated cleanup review</small></article></section><section className="panel"><div className="panelTitle"><h2>Largest categories</h2><span>Explainable rules</span></div>{categories.length ? <ul className="categoryList">{categories.map(([name, total]) => <li key={name}><span>{name}</span><div><i style={{ width: `${Math.max(4, total / categories[0][1] * 100)}%` }}/><b>{bytes(total)}</b></div></li>)}</ul> : <p className="muted">No files were found under this root.</p>}</section><section className="safety"><h2>Cleanup stays under your control</h2><p>Recommendations distinguish SAFE, LOW RISK, REVIEW, and HIGH RISK. DiskScope re-checks the selected path and moves eligible files to your system Trash/Recycle Bin only after confirmation.</p></section></>}</main></div>;
}
